// main.c — static test for transformer.h (no malloc, no VLA)
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>

// Centralized build options (single place to control alternative paths)
#include "build_config.h"

#include "storm.h"
#include "profiler.h"

#if USE_FLASH
#include "model_flash.h"
#endif

// Optional deterministic input vector (generated by python/gen_test_vector.py)
#if defined(__has_include)
#if __has_include("test_vector.h")
#include "test_vector.h"
#define HAS_TEST_VECTOR 1
#else
#define HAS_TEST_VECTOR 0
#endif
#else
#define HAS_TEST_VECTOR 0
#endif

#include "timer_sdk.h"

static void dump_model_flash_signature(void)
{
#if USE_FLASH
    // Print a few addresses + first bytes read back from flash.
    // This helps detect stale/unprogrammed external flash contents.
    uint8_t buf[16];
    int err;

    // printf("[TT] model.h symbols: conv0_W=%p conv0_B=%p g_act_scales_q31=%p\n",
    //       (void *)conv0_W, (void *)conv0_B, (void *)g_act_scales_q31);

#ifdef MODEL_S_INPUT
    {
        union {
            float f;
            uint32_t u;
        } v;
        v.f = (float)MODEL_S_INPUT;
        // printf("[TT] MODEL_S_INPUT_bits=0x%08lx\n", (unsigned long)v.u);
    }
#endif

    err = flash_read_bytes(conv0_W, buf, sizeof(buf));
    if (err)
    {
        printf("[TT] flash_read_bytes(conv0_W) failed: %d\n", err);
    }
    else
    {
        //printf("[TT] conv0_W[0..15] from flash: ");
        // for (int i = 0; i < (int)sizeof(buf); ++i)
        //    printf("%d%s", (int)(int8_t)buf[i], (i == (int)sizeof(buf) - 1) ? "\n" : ",");
    }

    err = flash_read_bytes(g_act_scales_q31, buf, sizeof(buf));
    if (err)
    {
        printf("[TT] flash_read_bytes(g_act_scales_q31) failed: %d\n", err);
    }
    else
    {
        const int32_t *p = (const int32_t *)buf;
        // printf("[TT] act_scales_q31[0..3] from flash: %ld,%ld,%ld,%ld\n",
        //        (long)p[0], (long)p[1], (long)p[2], (long)p[3]);
    }
#endif
}

static void dump_topk_q15(const int16_t *p, int n, int k)
{
    if (!p || n <= 0 || k <= 0)
        return;

    // Simple O(n*k) selection (small n=64 typical).
    int idx[4] = {-1, -1, -1, -1};
    int16_t val[4] = {-(int16_t)32768, -(int16_t)32768, -(int16_t)32768, -(int16_t)32768};
    if (k > 4)
        k = 4;

    for (int i = 0; i < n; ++i)
    {
        int16_t v = p[i];
        for (int j = 0; j < k; ++j)
        {
            if (v > val[j])
            {
                // shift down
                for (int t = k - 1; t > j; --t)
                {
                    val[t] = val[t - 1];
                    idx[t] = idx[t - 1];
                }
                val[j] = v;
                idx[j] = i;
                break;
            }
        }
    }

    for (int j = 0; j < k; ++j)
    {
        printf("  #%d: t=%d q15=%d\n", j, idx[j], (int)val[j]);
    }
}

static void dump_i8_prefix(const char *name, const int8_t *x, int n, int max_print)
{
    if (!x || n <= 0)
        return;
    if (max_print > n)
        max_print = n;
    printf("[TT] %s (int8) prefix[%d]: ", name ? name : "vec", max_print);
    for (int i = 0; i < max_print; ++i)
        printf("%d%s", (int)x[i], (i == max_print - 1) ? "\n" : ",");
}

static void dump_topk_i32(const int32_t *x, int n, int k)
{
    if (!x || n <= 0 || k <= 0)
        return;
    if (k > 4)
        k = 4;
    int idx[4] = {-1, -1, -1, -1};
    int32_t val[4] = {INT32_MIN, INT32_MIN, INT32_MIN, INT32_MIN};
    for (int i = 0; i < n; ++i)
    {
        int32_t v = x[i];
        for (int j = 0; j < k; ++j)
        {
            if (v > val[j])
            {
                for (int t = k - 1; t > j; --t)
                {
                    val[t] = val[t - 1];
                    idx[t] = idx[t - 1];
                }
                val[j] = v;
                idx[j] = i;
                break;
            }
        }
    }
    for (int j = 0; j < k; ++j)
        printf("  #%d: t=%d val=%ld\n", j, idx[j], (long)val[j]);
}

void prof_hw_init(void)
{
    // Inizializza il timer per contare i clock
    timer_cycles_init();
    // Avvia il timer in modalità free-running
    timer_start();
}

uint64_t prof_now(void)
{
    // Legge il valore corrente del timer HW.
    return (uint64_t)timer_get_cycles();
}

// ---------------------------
// Compile-time configuration
// ---------------------------
// Fixed sequence length for the test (must match your kernels' assumptions)
#define T 64
// Classifier output tiling for streamed FC
#define OC_BLK 32

// Derive constants at compile-time (no VLAs)
enum
{
    C_IN = MODEL_IN_CHANNELS,
    C = MODEL_D_MODEL,
    TOKENS = T,
    WIN_LEN = (MODEL_ATTENTION_WINDOW <= 0 || MODEL_ATTENTION_WINDOW >= TOKENS)
                     ? TOKENS
                     : (2 * MODEL_ATTENTION_WINDOW + 1),
    // Hidden size = OUT of block0 MLP.FC1 (6-per-block layout: index 4 = blk0.mlp.fc1)
    H = FC4_OUT
};

// -------- Determine the maximum hidden size across blocks (for shared FC tiles) --------
// fc index layout (from exporter, 6 per block — split Q/K/V):
//   6*i+0: blk{i}.mha.q,    6*i+1: blk{i}.mha.k,    6*i+2: blk{i}.mha.v,
//   6*i+3: blk{i}.mha.proj, 6*i+4: blk{i}.mlp.fc1,  6*i+5: blk{i}.mlp.fc2
//   then: attnpool.fc0, attnpool.fc1, classifier
// mlp.fc1 is at index 6*i+4: depth=1 -> FC4_OUT, depth=2 -> FC4/FC10, etc.
#if MODEL_DEPTH == 1
#define H_MAX (FC4_OUT)
#elif MODEL_DEPTH == 2
#define H_MAX ((FC4_OUT > FC10_OUT) ? FC4_OUT : FC10_OUT)
#elif MODEL_DEPTH == 3
#define H_MAX (((FC4_OUT > FC10_OUT) ? FC4_OUT : FC10_OUT) > FC16_OUT \
                      ? ((FC4_OUT > FC10_OUT) ? FC4_OUT : FC10_OUT)      \
                      : FC16_OUT)
#elif MODEL_DEPTH == 4
#define H_MAX (((FC4_OUT > FC10_OUT) ? FC4_OUT : FC10_OUT) > \
               ((FC16_OUT > FC22_OUT) ? FC16_OUT : FC22_OUT) \
                      ? ((FC4_OUT > FC10_OUT) ? FC4_OUT : FC10_OUT) \
                      : ((FC16_OUT > FC22_OUT) ? FC16_OUT : FC22_OUT))
#else
#define H_MAX (FC4_OUT) /* extend similarly if you build deeper */
#endif
#define WMAX ((H_MAX > C) ? H_MAX : C)

// Basic sanity (compile-time where possible)
#if (MODEL_D_MODEL % MODEL_NHEAD) != 0
#error "d_model must be divisible by nhead"
#endif

// ---------------------------
// Workspace buffers (no malloc)
// Default: explicit static buffers (current flow).
// Optional: single arena + aliasing (alternative path only).
// ---------------------------
// Input & output
static int8_t g_x_in[C_IN * TOKENS];
static int32_t g_logits[MODEL_NUM_CLASSES];

// Ping-pong slabs [C,T]
static int8_t g_slab_a[C * TOKENS] __attribute__((aligned(4)));
static int8_t g_slab_b[C * TOKENS] __attribute__((aligned(4)));

// Stem
static int32_t g_stem_acc_line[CONV1D_OUT_TILE];
static int8_t g_stem_wbuf0[CONV1D_OUT_TILE * CONV0_INC * CONV0_K] __attribute__((aligned(4)));
static int8_t g_stem_wbuf1[CONV1D_OUT_TILE * CONV0_INC * CONV0_K] __attribute__((aligned(4)));
static int32_t g_stem_bbuf[CONV1D_OUT_TILE];
static int32_t g_stem_mbuf[CONV1D_OUT_TILE];
static int32_t g_stem_rbuf[CONV1D_OUT_TILE];

// PosMix
static int32_t g_pos_acc_scalar[1];
static int8_t g_pos_kbuf[CONV1_K];
static int32_t g_pos_bmr[3];

// Shared FC tiles
static int32_t g_acc_tile[FC_OUT_TILE];
static int8_t g_wbuf0_fc[FC_OUT_TILE * WMAX] __attribute__((aligned(4)));
static int8_t g_wbuf1_fc[FC_OUT_TILE * WMAX] __attribute__((aligned(4)));
static int32_t g_bbuf_fc[FC_OUT_TILE];
static int32_t g_mbuf_fc[FC_OUT_TILE];
static int32_t g_rbuf_fc[FC_OUT_TILE];

// MHSA work
static int32_t g_mhsa_scores_row[WIN_LEN];
static int16_t g_mhsa_probs_q15[WIN_LEN];
static int8_t g_mhsa_buf_qkv[3 * C * TOKENS] __attribute__((aligned(4)));
static int8_t g_mhsa_buf_tok[C] __attribute__((aligned(4)));

// MLP slabs
static int8_t g_mlp_H1[H * TOKENS] __attribute__((aligned(4)));
static int8_t g_mlp_H1A[H * TOKENS]; // could alias to save RAM
static int8_t g_mlp_tok[(H > C) ? H : C];

// AttnPool
static int32_t g_ap_logits_T[TOKENS];
static int16_t g_ap_probs_q15[TOKENS];

// Classifier tiles
static int8_t g_cls_w_tile[OC_BLK * C];
static int32_t g_cls_b_tile[OC_BLK];
static int8_t g_cls_tmp_i8[WMAX];
static int8_t g_cls_feat_preln_i8[C];

// Profiler global instance (used by transformer.h instrumentation)
#ifdef ENABLE_PROFILER
Profiler g_profiler;

static const char *prof_section_name(ProfSectionId id)
{
    switch (id)
    {
    case PROF_CONVSTEM:
        return "ConvStem";
    case PROF_POSMIX:
        return "PosMix";
    case PROF_MHSA_0:
        return "MHSA[0]";
    case PROF_MHSA_1:
        return "MHSA[1]";
    case PROF_MLP_0:
        return "MLP[0]";
    case PROF_MLP_1:
        return "MLP[1]";
    case PROF_FINAL_LN:
        return "Final LN";
    case PROF_ATTENPOOL:
        return "AttnPool";
    case PROF_CLASSIFIER:
        return "Classifier";
    default:
        return "UNKNOWN";
    }
}

// Dump profiler stats using only 32-bit prints, no float / int64 in printf.
static void dump_profiler_stats(void)
{
    int i;
    uint32_t cumsum_ticks32 = 0;

    printf("==== TinyTransformer profiler (ticks, truncated 32-bit) ====\n");
    for (i = 0; i < PROF_SECTION_COUNT; ++i)
    {
        const ProfEntry *e = &g_profiler.sections[i];

        if (e->calls == 0 && e->total_ticks == 0) {
            printf("  %-18s : <no data>\n",
                   prof_section_name((ProfSectionId)i));
            continue;
        }

        // Truncate 64-bit tick counter to 32-bit for printing.
        uint32_t total_ticks32 = (uint32_t)(e->total_ticks & 0xFFFFFFFFu);
        uint32_t calls32       = (uint32_t)(e->calls);

        const char *name = prof_section_name((ProfSectionId)i);

        printf("  %-18s : calls = %d, total_ticks = %d\n",
               name,
               (int)calls32,
               (int)total_ticks32);

        cumsum_ticks32 += total_ticks32;
    }
    printf("  %-18s : cumulative_ticks = %d\n", "CUMULATIVE", (int)cumsum_ticks32);
    printf("==========================================================\n");
}

#endif /* ENABLE_PROFILER */

// ---------------------------
// Helpers (no dynamic memory)
// ---------------------------
static inline float q31_to_float(uint32_t q31)
{
    return ((float)q31) / 2147483648.0f; // 2^31
}

static inline float get_act_scale(int idx) { return act_scale_from_q31_idx(idx); }

static void dump_f32_bits_prefix(const char *label, const float *p, int n)
{
    printf("%s bits prefix[%d]:\n", label, n);
    for (int i = 0; i < n; ++i)
    {
        union {
            float f;
            uint32_t u;
        } v;
        v.f = p[i];
        printf("  [%d] 0x%08x\n", i, (unsigned int)v.u);
    }
}

// simple deterministic PRNG
static uint32_t prng_state = 0x12345678u;
static inline uint32_t prng_next(void)
{
    // xorshift32
    uint32_t x = prng_state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    prng_state = x;
    return x;
}
static void fill_rand_i8(int8_t *p, size_t n)
{
    for (size_t i = 0; i < n; ++i)
    {
        p[i] = (int8_t)((int)(prng_next() % 255) - 127); // [-127,127]
    }
}

// -----------------------------------------------------------------------------
// Human-readable error reporting for Status (from transformer.h)
// -----------------------------------------------------------------------------
static void report_error(int code)
{
    switch (code)
    {
    case OK:
        printf("[TT] OK\n");
        return;
    case ERR_BAD_ARGS:
        printf("[TT] BAD ARGS: null pointer or T<=0\n");
        return;
    case ERR_ACT_SCALES_COUNT_MISMATCH:
        printf("[TT] Activation scales count mismatch\n");
        return;
    case ERR_CONV_TOUT_MISMATCH:
        printf("[TT] ConvStem output length mismatch (stride/pad/dil settings)\n");
        return;

    case ERR_RD_LN_BLK0_MHA_GAMMA:
        printf("[TT] FLASH read failed: LN blk0 MHA gamma\n");
        return;
    case ERR_RD_LN_BLK0_MHA_BETA:
        printf("[TT] FLASH read failed: LN blk0 MHA beta\n");
        return;
    case ERR_RD_LN_BLK0_MLP_GAMMA:
        printf("[TT] FLASH read failed: LN blk0 MLP gamma\n");
        return;
    case ERR_RD_LN_BLK0_MLP_BETA:
        printf("[TT] FLASH read failed: LN blk0 MLP beta\n");
        return;
    case ERR_RD_LN_BLK1_MHA_GAMMA:
        printf("[TT] FLASH read failed: LN blk1 MHA gamma\n");
        return;
    case ERR_RD_LN_BLK1_MHA_BETA:
        printf("[TT] FLASH read failed: LN blk1 MHA beta\n");
        return;
    case ERR_RD_LN_BLK1_MLP_GAMMA:
        printf("[TT] FLASH read failed: LN blk1 MLP gamma\n");
        return;
    case ERR_RD_LN_BLK1_MLP_BETA:
        printf("[TT] FLASH read failed: LN blk1 MLP beta\n");
        return;
    case ERR_RD_LN_BLK2_MHA_GAMMA:
        printf("[TT] FLASH read failed: LN blk2 MHA gamma\n");
        return;
    case ERR_RD_LN_BLK2_MHA_BETA:
        printf("[TT] FLASH read failed: LN blk2 MHA beta\n");
        return;
    case ERR_RD_LN_BLK2_MLP_GAMMA:
        printf("[TT] FLASH read failed: LN blk2 MLP gamma\n");
        return;
    case ERR_RD_LN_BLK2_MLP_BETA:
        printf("[TT] FLASH read failed: LN blk2 MLP beta\n");
        return;
    case ERR_RD_LN_BLK3_MHA_GAMMA:
        printf("[TT] FLASH read failed: LN blk3 MHA gamma\n");
        return;
    case ERR_RD_LN_BLK3_MHA_BETA:
        printf("[TT] FLASH read failed: LN blk3 MHA beta\n");
        return;
    case ERR_RD_LN_BLK3_MLP_GAMMA:
        printf("[TT] FLASH read failed: LN blk3 MLP gamma\n");
        return;
    case ERR_RD_LN_BLK3_MLP_BETA:
        printf("[TT] FLASH read failed: LN blk3 MLP beta\n");
        return;
    case ERR_RD_LN_FINAL_GAMMA:
        printf("[TT] FLASH read failed: LN final gamma\n");
        return;
    case ERR_RD_LN_FINAL_BETA:
        printf("[TT] FLASH read failed: LN final beta\n");
        return;
    case ERR_RD_LN_AP_GAMMA:
        printf("[TT] FLASH read failed: LN attnpool gamma\n");
        return;
    case ERR_RD_LN_AP_BETA:
        printf("[TT] FLASH read failed: LN attnpool beta\n");
        return;
    case ERR_RD_LN_CLS_GAMMA:
        printf("[TT] FLASH read failed: LN classifier gamma\n");
        return;
    case ERR_RD_LN_CLS_BETA:
        printf("[TT] FLASH read failed: LN classifier beta\n");
        return;

    case ERR_RD_ACT_SCALES:
        printf("[TT] FLASH read failed: activation scales (Q31)\n");
        return;

    // AttnPool streamed mapping
    case ERR_AP_BAD_ARGS:
        printf("[TT][AttnPool] bad args / geometry\n");
        return;
    case ERR_AP_RD_FC0_B:
        printf("[TT][AttnPool] FLASH read failed: FC0 bias tile\n");
        return;
    case ERR_AP_RD_FC0_M:
        printf("[TT][AttnPool] FLASH read failed: FC0 M tile\n");
        return;
    case ERR_AP_RD_FC0_R:
        printf("[TT][AttnPool] FLASH read failed: FC0 R tile\n");
        return;
    case ERR_AP_RD_FC0_W:
        printf("[TT][AttnPool] FLASH read failed: FC0 weights tile\n");
        return;
    case ERR_AP_RD_FC1_B:
        printf("[TT][AttnPool] FLASH read failed: FC1 bias\n");
        return;
    case ERR_AP_RD_FC1_M:
        printf("[TT][AttnPool] FLASH read failed: FC1 M\n");
        return;
    case ERR_AP_RD_FC1_R:
        printf("[TT][AttnPool] FLASH read failed: FC1 R\n");
        return;
    case ERR_AP_RD_FC1_W:
        printf("[TT][AttnPool] FLASH read failed: FC1 weights\n");
        return;
    case ERR_AP_UNKNOWN:
        printf("[TT][AttnPool] unknown error code from kernel\n");
        return;

    // Classifier streamed mapping
    case ERR_CLS_BAD_ARGS:
        printf("[TT][Classifier] bad args / tiles\n");
        return;
    case ERR_CLS_RD_BIAS:
        printf("[TT][Classifier] FLASH read failed: bias tile\n");
        return;
    case ERR_CLS_RD_M:
        printf("[TT][Classifier] FLASH read failed: M (requant scale) tile\n");
        return;
    case ERR_CLS_RD_R:
        printf("[TT][Classifier] FLASH read failed: R (requant shift) tile\n");
        return;
    case ERR_CLS_RD_WEIGHTS:
        printf("[TT][Classifier] FLASH read failed: weights tile\n");
        return;
    default:
        printf("[TT] Unknown error code: %d\n", code);
        return;
    }
}

// ---------------------------
// Main
// ---------------------------
int main(void)
{
    printf("STORM test\n");

#ifndef VERBOSE_DUMPS
#define VERBOSE_DUMPS 0
#endif

    // Enable FP for LayerNorm
    CSR_SET_BITS(CSR_REG_MSTATUS, (0x01u << 13)); // FS=01

    // Inizializza il timer HW del profiler
#ifdef ENABLE_PROFILER
    prof_hw_init();
    PROF_RESET_GLOBAL();
#endif

    // SPI init (only if using external flash)
#if USE_FLASH
    if (w25q128jw_init(spi_flash) != FLASH_OK)
    {
        printf("SPI flash init error\n");
        return EXIT_FAILURE;
    }
#endif

    dump_model_flash_signature();

    // 2) Build workspace struct
    Workspace ws;
    ws = (Workspace){
        .slab_a_ct = g_slab_a,
        .slab_b_ct = g_slab_b,

        .stem_acc_line = g_stem_acc_line,
        .stem_wbuf0 = g_stem_wbuf0,
        .stem_wbuf1 = g_stem_wbuf1,
        .stem_bbuf = g_stem_bbuf,
        .stem_mbuf = g_stem_mbuf,
        .stem_rbuf = g_stem_rbuf,

        .pos_acc_scalar = g_pos_acc_scalar,
        .pos_kbuf = g_pos_kbuf,
        .pos_bmr = g_pos_bmr,

        .acc_tile = g_acc_tile,
        .wbuf0_fc = g_wbuf0_fc,
        .wbuf1_fc = g_wbuf1_fc,
        .bbuf_fc = g_bbuf_fc,
        .mbuf_fc = g_mbuf_fc,
        .rbuf_fc = g_rbuf_fc,

        .mhsa_scores_row = g_mhsa_scores_row,
        .mhsa_probs_q15 = g_mhsa_probs_q15,
        .mhsa_buf_qkv = g_mhsa_buf_qkv,
        .mhsa_buf_tok = g_mhsa_buf_tok,

        .mlp_H1 = g_mlp_H1,
        .mlp_H1A = g_mlp_H1A,
        .mlp_tok = g_mlp_tok,

        .ap_logits_T = g_ap_logits_T,
        .ap_probs_q15 = g_ap_probs_q15,

        .cls_w_tile = g_cls_w_tile,
        .cls_b_tile = g_cls_b_tile,
        .cls_tmp_i8 = g_cls_tmp_i8,
        .cls_feat_preln_i8 = g_cls_feat_preln_i8};

    // 3) Runtime parameters
    // IMPORTANT: activation scales are read from an SRAM cache that is populated by
    // transformer_preload_constants_to_sram(). If you read scales before preloading,
    // you will get zeros and LayerNorm will collapse to all-zeros.
    {
        int prc = transformer_preload_constants_to_sram();
        if (prc != OK) {
            printf("transformer_preload_constants_to_sram failed: %d\n", prc);
            report_error(prc);
            return prc;
        }
    }

    Params params;
    params_from_export_defaults(&params);

#ifdef ENABLE_PROFILER
    PROF_RESET_GLOBAL();
#endif

    // 4) Run (single or sweep)
#if HAS_TEST_VECTOR
#ifndef TEST_VECTOR_COUNT
#define TEST_VECTOR_COUNT 1
#endif

    // test_vector.h defines g_test_x_in as flattened buffer. For COUNT>1 it is concatenated.
    if (TEST_VECTOR_CIN != C_IN || TEST_VECTOR_T != TOKENS)
    {
        printf("[TT] test_vector.h geometry mismatch: got (Cin=%d,T=%d) expected (Cin=%d,T=%d)\n",
               (int)TEST_VECTOR_CIN, (int)TEST_VECTOR_T, (int)C_IN, (int)TOKENS);
        return EXIT_FAILURE;
    }

    const int stride = (int)C_IN * (int)TOKENS;
    int pass = 0;
    int pred_hist[MODEL_NUM_CLASSES] = {0};
    int label_hist[MODEL_NUM_CLASSES] = {0};
    int have_labels = 0;

    for (int vi = 0; vi < (int)TEST_VECTOR_COUNT; ++vi)
    {
        const int8_t *src = &g_test_x_in[vi * stride];
        memcpy(g_x_in, src, sizeof(g_x_in));

        int vec_id = (int)TEST_VECTOR_ID;
        int label = (int)TEST_VECTOR_LABEL;
#ifdef TEST_VECTOR_HAS_TABLES
        vec_id = (int)g_test_vector_ids[vi];
        label  = (int)g_test_vector_labels[vi];
#endif

        printf("[TT] vec %d/%d id=%d label=%d -> ",
               vi + 1, (int)TEST_VECTOR_COUNT, vec_id, label);

        int rc = transformer_forward_i8_flash(g_x_in, TOKENS, &params, &ws, g_logits);
        if (rc)
        {
            printf("ERR(rc=%d)\n", rc);
            report_error(rc);
            continue;
        }

        int best = 0;
        for (int i = 1; i < MODEL_NUM_CLASSES; ++i)
            if (g_logits[i] > g_logits[best])
                best = i;

        int ok = (label >= 0) ? (best == label) : 1;
        if (ok) pass++;
        if (best >= 0 && best < MODEL_NUM_CLASSES) pred_hist[best]++;
        if (label >= 0 && label < MODEL_NUM_CLASSES) { label_hist[label]++; have_labels = 1; }
        printf("pred=%d %s\n", best, ok ? "OK" : "FAIL");

#if VERBOSE_DUMPS
        printf("  logits:\n");
        for (int i = 0; i < MODEL_NUM_CLASSES; ++i)
            printf("    [%d] %d\n", i, g_logits[i]);
#endif
    }

    printf("[TT] Summary: %d/%d correct\n", pass, (int)TEST_VECTOR_COUNT);

#else
    uint32_t seed0 = prng_state;
    fill_rand_i8(g_x_in, (size_t)C_IN * (size_t)TOKENS);
    printf("[TT] Using PRNG input (seed=0x%08x)\n", (unsigned int)seed0);

    printf("Running transformer_forward_i8_flash...\n");
    int rc = transformer_forward_i8_flash(g_x_in, TOKENS, &params, &ws, g_logits);
    if (rc)
    {
        printf("transformer_forward_i8_flash failed: %d\n", rc);
        report_error(rc);
        return rc;
    }
    int best = 0;
    for (int i = 1; i < MODEL_NUM_CLASSES; ++i)
        if (g_logits[i] > g_logits[best])
            best = i;
    printf("Argmax: %d\n", best);
#endif

#ifdef ENABLE_PROFILER
    printf("\nProfiler results:\n");
    dump_profiler_stats();
#endif

    return 0;
}